<?php
/**
 * s => String
 * i => Integer/number
 * d => Double
 * f => Float
 * 
 * index 0 = Data Field
 * index 1 = Data Type
 * index 2 = Data Length
 * index 3 = Field Description
*/
return 
[
 ['CCCODE','s', 20]
,['MERCHANT_NAME','s', 60]
,['TER_NO','i', 3]
,['TRN_DATE','s', 10]
,['STRANS','i', 15]
,['ETRANS','i', 15]
,['GROSS_SLS','d', 12]
,['VAT_AMNT','d', 12]
,['VATABLE_SLS','d', 12]
,['NONVAT_SLS','d', 12]
,['VATEXEMPT_SLS','d', 12]
,['VATEXEMPT_AMNT','d', 12]
,['OLD_GRNTOT','d', 12]
,['NEW_GRNTOT','d', 12]
,['LOCAL_TAX','d', 12]
,['VOID_AMNT','d', 12]
,['NO_VOID','i', 6]
,['DISCOUNTS','d', 12]
,['NO_DISC','i', 6]
,['REFUND_AMT','d', 12]
,['NO_REFUND','i', 6]
,['SNRCIT_DISC','d', 12]
,['NO_SNRCIT','i', 6]
,['PWD_DISC','d', 12]
,['NO_PWD','i', 6]
,['EMPLO_DISC','d', 12]
,['NO_EMPLO','i', 6]
,['AYALA_DISC','d', 12]
,['NO_AYALA','i', 6]
,['STORE_DISC','d', 12]
,['NO_STORE','i', 6]
,['OTHER_DISC','d', 12]
,['NO_OTHER_DISC','i', 6]
,['SCHRGE_AMT','d', 12]
,['OTHER_SCHR','d', 12]
,['CASH_SLS','d', 12]
,['CARD_SLS','d', 12]
,['EPAY_SLS','d', 12]
,['DCARD_SLS','d', 12]
,['OTHER_SLS','d', 12]
,['CHECK_SLS','d', 12]
,['GC_SLS','d', 12]
,['MASTERCARD_SLS','d', 12]
,['VISA_SLS','d', 12]
,['AMEX_SLS','d', 12]
,['DINERS_SLS','d', 12]
,['JCB_SLS','d', 12]
,['GCASH_SLS','d', 12]
,['PAYMAYA_SLS','d', 12]
,['ALIPAY_SLS','d', 12]
,['WECHAT_SLS','d', 12]
,['GRAB_SLS','d', 12]
,['FOODPANDA_SLS','d', 12]
,['MASTERDEBIT_SLS','d', 12]
,['VISADEBIT_SLS','d', 12]
,['PAYPAL_SLS','d', 12]
,['ONLINE_SLS','d', 12]
,['OPEN_SALES','d', 12]
,['OPEN_SALES_2','d', 12]
,['OPEN_SALES_3','d', 12]
,['OPEN_SALES_4','d', 12]
,['OPEN_SALES_5','d', 12]
,['OPEN_SALES_6','d', 12]
,['OPEN_SALES_7','d', 12]
,['OPEN_SALES_8','d', 12]
,['OPEN_SALES_9','d', 12]
,['OPEN_SALES_10','d', 12]
,['OPEN_SALES_11','d', 12]
,['GC_EXCESS','d', 12]
,['NO_VATEXEMT','i', 6]
,['NO_SCHRGE','i', 6]
,['NO_OTHER_SUR','i', 6]
,['NO_CASH','i', 6]
,['NO_CARD','i', 6]
,['NO_EPAY','i', 6]
,['NO_DCARD_SLS','i', 6]
,['NO_OTHER_SLS','i', 6]
,['NO_CHECK','i', 6]
,['NO_GC','i', 6]
,['NO_MASTERCARD_SLS','i', 6]
,['NO_VISA_SLS','i', 6]
,['NO_AMEX_SLS','i', 6]
,['NO_DINERS_SLS','i', 6]
,['NO_JCB_SLS','i', 6]
,['NO_GCASH_SLS','i', 6]
,['NO_PAYMAYA_SLS','i', 6]
,['NO_ALIPAY_SLS','i', 6]
,['NO_WECHAT_SLS','i', 6]
,['NO_GRAB_SLS','i', 6]
,['NO_FOODPANDA_SLS','i', 6]
,['NO_MASTERDEBIT_SLS','i', 6]
,['NO_VISADEBIT_SLS','i', 6]
,['NO_PAYPAL_SLS','i', 6]
,['NO_ONLINE_SLS','i', 6]
,['NO_OPEN_SALES','i', 6]
,['NO_OPEN_SALES_2','i', 6]
,['NO_OPEN_SALES_3','i', 6]
,['NO_OPEN_SALES_4','i', 6]
,['NO_OPEN_SALES_5','i', 6]
,['NO_OPEN_SALES_6','i', 6]
,['NO_OPEN_SALES_7','i', 6]
,['NO_OPEN_SALES_8','i', 6]
,['NO_OPEN_SALES_9','i', 6]
,['NO_OPEN_SALES_10','i', 6]
,['NO_OPEN_SALES_11','i', 6]
,['NO_NOSALE','i', 6]
,['NO_CUST','i', 6]
,['NO_TRN','i', 6]
,['PREV_EODCTR','i', 6]
,['EODCTR','i', 6]
];
